version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: profiremanager-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: changeme
      MONGO_INITDB_DATABASE: profiremanager_dev

  backend:
    build: ./backend
    container_name: profiremanager-backend
    ports:
      - "8001:8001"
    environment:
      MONGO_URL: mongodb://admin:changeme@mongodb:27017/profiremanager_dev?authSource=admin
      DB_NAME: profiremanager_dev
      CORS_ORIGINS: http://localhost:3000
      JWT_SECRET: dev-secret-key-not-for-production
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: profiremanager-frontend
    ports:
      - "3000:80"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8001
    depends_on:
      - backend

volumes:
  mongodb_data:
